// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
/* tslint:disable */
let _VERSION = '0.0.1-SNAPSHOT'; // This value will be overwritten by webpack
let _DEBUG_INFO_ENABLED = true; // This value will be overwritten by webpack
let _AVAILABLE_LANGUAGES = ['es', 'en', 'ca'];
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
/* @toreplace AVAILABLE_LANGUAGES */
/* tslint:enable */
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;
export const AVAILABLE_LANGUAGES = _AVAILABLE_LANGUAGES;
export const TOKEN_AUTH_NAME = 'authenticationtoken';
export const JHI_TOKEN_AUTH_NAME = 'jhi-authenticationtoken';
export const BASE_DECIMAL = 10;
export const ERROR_ALERT_KEY = 'alert-errors';
export const LANG_KEY = 'lang';
export const DEFAULT_LANG = 'es';

export const DEFAULT_PATH = '/filter';

export const PAGINATION_OPTIONS = [100, 150, 200];
export const ITEMS_PER_PAGE = PAGINATION_OPTIONS[0];
