version: '2'
services:
    edatos_external_users-app:
        image: edatos_external_users
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://edatos_external_users-postgresql:5432/edatos_external_users
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    edatos_external_users-postgresql:
        extends:
            file: postgresql.yml
            service: edatos_external_users-postgresql
