version: '2'
services:
    edatos_external_users-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/edatos_external_users/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=edatos_external_users
            - POSTGRES_PASSWORD=edatos_external_users
            - POSTGRES_DB=dev
        ports:
            - 5432:5432
