version: '2'
services:
    statistical_operations_roadmap-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/statistical_operations_roadmap/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=statistical_operations_roadmap
            - POSTGRES_PASSWORD=statistical_operations_roadmap
            - POSTGRES_DB=dev
        ports:
            - 5432:5432
