# ===================================================================
# Spring Boot configuration for the "env" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        show-sql: false
    mail:
        host: FILL_HOST
        port: FILL_PORT
        username: FILL_USER
        password: FILL_PASS

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    mail: 
        from: FILL_EMAIL
        base-url: http://FILL_APPLICATION_URL 

# ===================================================================
# Application specific properties
# Add your own application properties here.
# ===================================================================
environment:
    edatos:
        configuration:
            db:
                driverName: FILL_ME
                url: FILL_ME
                username: FILL_ME
                password: FILL_ME

application:
    metadata:
        endpoint: FILL_ME
    endpoint:
        # Required: Aplication URL
        app-url: FILL_APP_URL
    cas:
        endpoint: FILL_ENDPOINT_URL # Required: Cas Endpoint
        service:  FILL_SERVICE_URL # Required: Aplication service
        login: # Optional: Only change if needed (Leave empty for cas.enpoint + '/login')
        logout: # Optional: Only change if needed(Leave empty for cas.enpoint + '/logout')

# ===================================================================        
# Application debug properties
#
# Uncomment if debug mode needed
# ===================================================================

# debug
