# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


endpoints:
    enabled: false
    configprops:
        enabled: true
    health:
        enabled: true
    env:
        enabled: true

management:
    security:
        enabled: false
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: edatos_external_users
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        database-platform: io.github.jhipster.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
            hibernate.cache.provider_class: ehcache
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    # spring.jmx.default-domain y spring.hikari.pool-name evitan que al levantar dos aplicaciones con un spring boot similar al template
    # (con beans de jmx configurado) la primera registre sus beans impidiendo a las siguientes registrar los suyos
    jmx:
        default-domain: edatos_external_users
    hikari:
        pool-name: edatos_external_users_pool
    mail:
        host: FILL_HOST
        port: FILL_PORT
        username: FILL_USER
        password: FILL_PASS
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
    messages:
        basename: i18n/messages-external_users
    mvc:
        favicon:
            enabled: false
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    thymeleaf:
        cache: true
        mode: XHTML
        prefix: /

security:
    basic:
        enabled: false

info:
    project:
        version: #project.version#


# ===================================================================
# Liquidbase specific properties
# ===================================================================

liquibase:
    contexts: prod


# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias edatos_external_users -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        keyStoreType: PKCS12
#        keyAlias: edatos_external_users
# ===================================================================
server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
    session:
        cookie:
            http-only: true


# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
        # By default CORS is disabled. Uncomment to enable.
        #cors:
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: 166deddd007daacd095972fad770947e96a537c4
                # 10 hours and 1 minute
                token-validity-in-seconds: 36001
                # 30 days
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: edatos_external_users@localhost
        base-url: http://my-server-url-to-change # Modify according to your server's URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
    ribbon:
        display-on-active-profiles: dev

jhipster-extra:
    security:
        authentication:
            jwt:
                # 30 minutes
                token-renew-period-in-seconds: 1800
# ===================================================================
# Change log levels
# ===================================================================

logging:
    level:
        org.hibernate.orm.deprecation: ERROR

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================

application:
    metadata:
        metamacNavbarKey: metamac.navbar.url
        metamacCasPrefixKey: metamac.security.cas_server_url_prefix
        metamacCasLoginUrlKey: metamac.security.cas_service_login_url
        metamacCasLogoutUrlKey: metamac.security.cas_service_logout_url
        metamacFaviconUrlKey: metamac.app.style.favicon.url
        metamacHeaderUrlKey: metamac.api.style.header.url
        metamacFooterUrlKey: metamac.api.style.footer.url
    endpoint:
        # Required: Aplication URL
        app-url: FILL_APP_URL
    cas:
        endpoint: FILL_ENDPOINT_URL # Required: Cas Endpoint
        service: FILL_SERVICE_URL # Required: Aplication service
        login: # Optional: Only change if needed (Leave empty for cas.enpoint + '/login')
        logout: # Optional: Only change if needed(Leave empty for cas.enpoint + '/logout')
