-- ###########################################
-- # Drop
-- ###########################################


-- Disable Foreign key constraints
    

  
  
ALTER TABLE TB_EXTERNAL_ITEMS DROP CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK;

  
ALTER TABLE TB_CONFIGURATIONS DROP CONSTRAINT FK_TB_CONFIGURATIONS_LEGAL_ACTS_FK;
ALTER TABLE TB_CONFIGURATIONS DROP CONSTRAINT FK_TB_CONFIGURATIONS_DATA_SHARING_FK;
ALTER TABLE TB_CONFIGURATIONS DROP CONSTRAINT FK_TB_CONFIGURATIONS_CONF_POLICY_FK;
ALTER TABLE TB_CONFIGURATIONS DROP CONSTRAINT FK_TB_CONFIGURATIONS_CONF_DATA_TREATMENT_FK;
ALTER TABLE TB_CONFIGURATIONS DROP CONSTRAINT FK_TB_CONFIGURATIONS_CONTACT_FK;
ALTER TABLE TB_CONFIGURATIONS DROP CONSTRAINT FK_TB_CONFIGURATIONS_LICENSE_FK;

  
  
  
ALTER TABLE TB_LOCALISED_STRINGS DROP CONSTRAINT FK_TB_LOCALISED_STRINGS_INTERNATIONAL_STRING_FK;

  

    
    
-- Drop many to many relations
    
-- Drop normal entities
    
DROP TABLE TB_LOCALISED_STRINGS CASCADE;

DROP TABLE TB_DATA_CONFIGURATIONS CASCADE;

DROP TABLE TB_CONFIGURATIONS CASCADE;

DROP TABLE TB_EXTERNAL_ITEMS CASCADE;

DROP TABLE TB_INTERNATIONAL_STRINGS CASCADE;

DROP TABLE TB_SEQUENCES;