export enum Role {
    JEFE_NORMALIZACION = 'JEFE_NORMALIZACION',
    TECNICO_NORMALIZACION = 'TECNICO_NORMALIZACION',
    TECNICO_APOYO_NORMALIZACION = 'TECNICO_APOYO_NORMALIZACION',
    TECNICO_APOYO_PRODUCCION = 'TECNICO_APOYO_PRODUCCION',
    TECNICO_PRODUCCION = 'TECNICO_PRODUCCION',
    TECNICO_APOYO_DIFUSION = 'TECNICO_APOYO_DIFUSION',
    TECNICO_DIFUSION = 'TECNICO_DIFUSION',
    TECNICO_APOYO_PLANIFICACION = 'TECNICO_APOYO_PLANIFICACION',
    TECNICO_PLANIFICACION = 'TECNICO_PLANIFICACION',
    LECTOR = 'LECTOR',
    ADMINISTRADOR = 'ADMINISTRADOR',
    ANY_ROLE_ALLOWED = 'ANY_ROLE_ALLOWED',
}
